import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { setPageMeta } from '../lib/seo';
import { prettify, formatDate } from '../lib/format';
import { Button } from '../design-system/components/core/Button';
import { Badge } from '../design-system/components/core/Badge';
import { ContentCard } from '../design-system/components/content/ContentCard';
import { ArticleMeta } from '../design-system/components/content/ArticleMeta';
import { Spinner } from '../design-system/components/feedback/Spinner';
import { Alert } from '../design-system/components/feedback/Alert';
import heroImage from '../assets/hero.png';

interface PageDescriptor {
  slug: string;
  path: string;
}

interface PageSummary extends PageDescriptor {
  title: string;
  description: string;
  date?: string;
  author?: string;
  readingTime?: number;
  section: string;
}

const API_BASE = import.meta.env.VITE_API_BASE_URL ?? '';

/**
 * Home page: lists all available content pages fetched from GET /api/pages.
 *
 * This list is dynamically generated by the API, which walks the content/
 * directory at request time. Adding a new folder + index.md automatically
 * makes it appear here — no code changes required.
 *
 * The listing endpoint only returns { slug, path }; the hero/featured/grid
 * treatment needs richer metadata (title, description, date), so each
 * page's full record is fetched from the existing GET /api/content/:slug
 * endpoint in parallel — no new API surface required.
 */
export default function HomePage() {
  const navigate = useNavigate();
  const [pages, setPages] = useState<PageSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    setPageMeta({
      title: 'Acme Co. — Content Hub',
      description: 'Acme Co. marketing content hub — browse all pages.',
      url: window.location.origin + '/',
      image: `${window.location.origin}/og-image.png`,
      type: 'website',
      jsonLd: {
        '@context': 'https://schema.org',
        '@type': 'WebSite',
        name: 'Acme Co. Content Hub',
        url: window.location.origin + '/',
      },
      feedHref: `${API_BASE}/rss.xml`,
    });

    fetch(`${API_BASE}/api/pages`)
      .then(async (res) => {
        if (!res.ok) throw new Error();
        const descriptors = (await res.json()) as PageDescriptor[];
        const results = await Promise.allSettled(
          descriptors.map(async (d) => {
            const res2 = await fetch(`${API_BASE}/api/content/${d.slug}`);
            if (!res2.ok) throw new Error();
            const data = (await res2.json()) as Omit<PageSummary, 'path' | 'section'>;
            return { ...d, ...data, section: prettify(d.slug.split('/')[0]) };
          }),
        );
        setPages(
          results
            .filter((r): r is PromiseFulfilledResult<PageSummary> => r.status === 'fulfilled')
            .map((r) => r.value),
        );
      })
      .catch(() => setError(true))
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', padding: 'var(--space-16) 0' }}>
        <Spinner label="Loading pages" size="lg" />
      </div>
    );
  }

  if (error) {
    return <Alert tone="danger">Could not load pages. Make sure the API is running.</Alert>;
  }

  if (pages.length === 0) {
    return <Alert tone="info">No pages found.</Alert>;
  }

  const featured = pages.reduce((best, p) => ((p.date ?? '') > (best.date ?? '') ? p : best), pages[0]);
  const rest = pages.filter((p) => p !== featured);

  return (
    <div>
      {/* Hero */}
      <section style={{ paddingTop: 'var(--space-16)', paddingBottom: 'var(--space-12)' }}>
        <span className="eyebrow">Marketing Content Hub</span>
        <h1 style={{
          margin: 'var(--space-4) 0 0', maxWidth: '20ch',
          fontSize: 'var(--text-5xl)', lineHeight: 1.04, letterSpacing: '-0.02em',
          fontWeight: 600, color: 'var(--text-heading)',
        }}>
          Widgets, valves &amp; the business of{' '}
          <em style={{ fontStyle: 'italic', color: 'var(--accent-text)' }}>building things</em>.
        </h1>
        <p style={{
          margin: 'var(--space-6) 0 0', maxWidth: '52ch',
          fontFamily: 'var(--font-sans)', fontSize: 'var(--text-lg)', lineHeight: 'var(--leading-normal)',
          color: 'var(--text-muted)',
        }}>
          News, updates and product notes from Acme Co. — a reputable international maker of industrial
          products. Browse everything below.
        </p>
        <div style={{ display: 'flex', gap: 'var(--space-3)', marginTop: 'var(--space-8)', flexWrap: 'wrap' }}>
          <Button variant="primary" iconTrailing="arrow-right" onClick={() => navigate(featured.path)}>
            Read the latest
          </Button>
          <a href={`${API_BASE}/rss.xml`} style={{ textDecoration: 'none' }}>
            <Button variant="secondary" icon="rss">Subscribe</Button>
          </a>
        </div>
      </section>

      {/* Featured lead */}
      <section
        className="home-featured-grid"
        onClick={() => navigate(featured.path)}
        style={{
          display: 'grid', gap: 'var(--space-8)',
          alignItems: 'stretch', cursor: 'pointer',
          background: 'var(--surface-card)', border: '1px solid var(--border-subtle)',
          borderRadius: 'var(--radius-xl)', overflow: 'hidden', boxShadow: 'var(--shadow-sm)',
        }}
      >
        <div style={{ padding: 'var(--space-10)', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: 'var(--space-4)' }}>
          <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
            <Badge tone="accent" variant="solid">Featured</Badge>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--text-xs)', color: 'var(--text-subtle)', letterSpacing: 'var(--tracking-label)', textTransform: 'uppercase' }}>
              {featured.section}
            </span>
          </div>
          <h2 style={{ margin: 0, fontSize: 'var(--text-3xl)', lineHeight: 1.1, letterSpacing: '-0.015em', color: 'var(--text-heading)' }}>
            {featured.title}
          </h2>
          <p style={{ margin: 0, fontFamily: 'var(--font-serif)', fontSize: 'var(--text-lg)', lineHeight: 'var(--leading-normal)', color: 'var(--text-body)' }}>
            {featured.description}
          </p>
          <ArticleMeta
            author={featured.author}
            date={featured.date ? formatDate(featured.date) : undefined}
            readingTime={featured.readingTime}
            withAvatar
          />
        </div>
        <div aria-hidden="true" style={{
          background: 'linear-gradient(135deg, var(--violet-500), var(--violet-800))',
          display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: 260,
        }}>
          <img src={heroImage} alt="" style={{ width: '68%', maxWidth: 260, filter: 'drop-shadow(0 20px 40px rgba(0,0,0,0.35))' }} />
        </div>
      </section>

      {/* Content grid */}
      {rest.length > 0 && (
        <section style={{ marginTop: 'var(--space-16)' }}>
          <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between', marginBottom: 'var(--space-6)' }}>
            <h2 style={{ margin: 0, fontSize: 'var(--text-2xl)', color: 'var(--text-heading)' }}>All content</h2>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 'var(--text-xs)', color: 'var(--text-subtle)' }}>
              {pages.length} pages
            </span>
          </div>
          <div className="home-content-grid" style={{ display: 'grid', gap: 'var(--space-4)' }}>
            {rest.map((p) => (
              <ContentCard
                key={p.slug}
                eyebrow={p.section}
                title={p.title}
                description={p.description}
                href={p.path}
                onClick={(e) => { e.preventDefault(); navigate(p.path); }}
              />
            ))}
          </div>
        </section>
      )}
    </div>
  );
}
