import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

interface PageDescriptor {
  slug: string;
  path: string;
}

const API_BASE = import.meta.env.VITE_API_BASE_URL ?? '';

/**
 * Home page: lists all available content pages fetched from GET /api/pages.
 *
 * This list is dynamically generated by the API, which walks the content/
 * directory at request time.  Adding a new folder + index.md automatically
 * makes it appear here — no code changes required.
 */
export default function HomePage() {
  const [pages, setPages] = useState<PageDescriptor[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  useEffect(() => {
    document.title = 'Acme Co. — Content Hub';
    fetch(`${API_BASE}/api/pages`)
      .then(async (res) => {
        if (!res.ok) throw new Error();
        setPages((await res.json()) as PageDescriptor[]);
      })
      .catch(() => setError(true))
      .finally(() => setLoading(false));
  }, []);

  return (
    <div>
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white">
          Welcome to Acme Co.
        </h1>
        <p className="mt-2 text-gray-500 dark:text-gray-400">
          Browse our content below.
        </p>
      </div>

      {loading && (
        <div className="flex justify-center py-12" aria-label="Loading pages">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600" />
        </div>
      )}

      {error && (
        <p className="text-red-600 dark:text-red-400">
          Could not load pages. Make sure the API is running.
        </p>
      )}

      {!loading && !error && pages.length === 0 && (
        <p className="text-gray-500 dark:text-gray-400">No pages found.</p>
      )}

      {pages.length > 0 && (
        <ul className="grid gap-4 sm:grid-cols-2" role="list">
          {pages.map(({ slug, path }) => (
            <li key={slug}>
              <Link
                to={path}
                className="flex items-center justify-between p-4 rounded-lg border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 hover:border-blue-400 dark:hover:border-blue-500 hover:shadow-md transition-all group"
              >
                <span className="text-gray-900 dark:text-white font-medium group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">
                  {slug
                    .split('/')
                    .map((part) => part.replace(/-/g, ' '))
                    .join(' › ')}
                </span>
                <span
                  className="text-gray-400 dark:text-gray-500 group-hover:text-blue-400 transition-colors"
                  aria-hidden="true"
                >
                  →
                </span>
              </Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
